name: Install
description: "Sets up Node.js and runs install"

inputs:
  node-version:
    description: "Node.js versions to install"
    required: false
    default: "18"

  node-version-file:
    description: "Path to the Node.js version file. According to the specifications of actions/setup-node, if both node-version and node-version-file are provided as inputs, node-version takes precedence."
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: true
