name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@v4.1.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-please

    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          node-version-file: ".nvmrc"

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
